// TypeScript interfaces mirroring the Rust types from rdlp-desktop src-tauri.
//
// Serialization conventions:
//   - Rust structs without #[serde(rename_all)] use snake_case field names.
//   - Rust structs with #[serde(rename_all = "camelCase")] use camelCase.
//   - Rust Option<T> maps to T | null.
//   - Rust enums with #[serde(rename_all = "lowercase")] become string literals.

// ========== UI State Types ==========

/** Active view in the pane-based workspace. */
export type { AppView } from "../stores/uiStore";

// ========== Search Types ==========

/** A site that supports search (snake_case — default serde). */
export interface SearchSiteInfo {
    name: string;
    display_name: string;
}

/** A concrete filter key-value applied to a search. */
export interface SearchFilter {
    key: string;
    value: string;
}

/** Describes a filter a site supports (for UI construction). */
export interface SearchFilterDescriptor {
    key: string;
    display_name: string;
    allowed_values: SearchFilterValue[];
    default: string | null;
}

/** A single selectable value inside a filter descriptor. */
export interface SearchFilterValue {
    value: string;
    label: string;
}

/** A lightweight preview of a single search result. */
export interface SearchResultPreview {
    video_url: string;
    title: string;
    thumbnail_url: string | null;
    duration: number | null;
    uploader: string | null;
    uploader_url?: string | null;
    actors: string[];
    view_count: number | null;
    upload_date: string | null;
}

/** Response for a single search page with pagination metadata. */
export interface SearchPageResponse {
    results: SearchResultPreview[];
    page: number;
    has_more: boolean;
    total_estimate: number | null;
}

// ========== Format Types ==========

/** Frontend-facing format information (snake_case — default serde). */
export interface FormatInfo {
    format_id: string;
    ext: string;
    format_note: string | null;
    width: number | null;
    height: number | null;
    fps: number | null;
    tbr: number | null;
    vcodec: string | null;
    acodec: string | null;
    filesize: number | null;
    vbr: number | null;
    abr: number | null;
    asr: number | null;
    protocol: string;
    has_video: boolean;
    has_audio: boolean;
    /**
     * HLS audio-rendition group identifier.
     *
     * - On a video-only row: the `AUDIO="group-id"` referenced by the
     *   variant's `EXT-X-STREAM-INF` — i.e. the group it expects to be
     *   paired with.
     * - On an audio-only row: the row's own `EXT-X-MEDIA` `GROUP-ID`.
     *
     * Matching values indicate a compatible bv+ba pair. `null` outside HLS.
     */
    audio_group_id: string | null;
}

/** Subtitle availability for a single language. */
export interface SubtitleInfo {
    lang: string;
    formats: string[];
}

/** Complete response for the formats command. */
export interface FormatListResponse {
    title: string;
    formats: FormatInfo[];
    subtitles: SubtitleInfo[];
    thumbnail_url: string | null;
    duration: number | null;
    is_playlist: boolean;
    playlist: PlaylistInfo | null;
}

/** A single episode entry in a playlist (camelCase — Rust uses #[serde(rename_all = "camelCase")]). */
export interface PlaylistEntry {
    index: number;
    title: string;
    url: string;
    thumbnailUrl: string | null;
    duration: number | null;
    hasSub: boolean;
    hasDub: boolean;
}

/** Playlist metadata returned when a URL resolves to multiple episodes (camelCase). */
export interface PlaylistInfo {
    title: string;
    count: number;
    entries: PlaylistEntry[];
}

/** Playlist membership context for batch downloads (camelCase — matches Rust serde). */
export interface PlaylistContext {
    /** Shared UUID identifying this playlist batch (generated by frontend). */
    playlistId: string;
    /** Display title of the playlist/series. */
    playlistTitle: string;
    /** 1-based position of this episode in the playlist. */
    playlistIndex: number;
    /** Total number of episodes in the playlist. */
    playlistCount: number;
}

// ========== Video Codec Types (camelCase — Rust uses #[serde(rename_all = "camelCase")]) ==========

/** Info about a single video encoder available in the linked FFmpeg build. */
export interface VideoEncoderInfo {
    encoderName: string;
    displayName: string;
}

/** Info about a video codec with its available encoders. */
export interface VideoCodecInfo {
    codec: string;
    displayName: string;
    defaultContainer: string;
    encoders: VideoEncoderInfo[];
}

// ========== Audio Codec Types (camelCase — Rust uses #[serde(rename_all = "camelCase")]) ==========

/** Info about a single audio encoder available in the linked FFmpeg build. */
export interface AudioEncoderInfo {
    encoderName: string;
    displayName: string;
}

/** Info about an audio codec with its available encoders and compatible containers. */
export interface AudioCodecInfo {
    codec: string;
    displayName: string;
    encoders: AudioEncoderInfo[];
    /** ContainerFormat enum values serialized as lowercase strings (e.g. "mp4", "mkv"). */
    supportedContainers: string[];
}

/**
 * How to handle audio during video recode.
 *
 * Mirrors Rust `RecodeAudioMode` with `#[serde(tag = "mode")]`:
 *   { mode: "copy" } | { mode: "auto" } | { mode: "encoder", name: "libfdk_aac" }
 */
export type RecodeAudioMode =
    | { mode: "copy" }
    | { mode: "auto" }
    | { mode: "encoder"; name: string };

// ========== Download Types ==========

/**
 * Playlist membership context attached to a download job (camelCase — Rust uses #[serde(rename_all = "camelCase")]).
 *
 * Present only when the job is part of a playlist batch download.
 * All fields are required when the object is present.
 */
export interface PlaylistContext {
    playlistId: string;
    playlistTitle: string;
    /** 1-based position of this episode in the playlist. */
    playlistIndex: number;
    /** Total number of episodes in the playlist. */
    playlistCount: number;
}

/** Lifecycle status of a download job (#[serde(rename_all = "lowercase")]). */
export type JobStatus =
    | "pending"
    | "running"
    | "processing"
    | "completed"
    | "failed"
    | "cancelled";

/** Active unit info owned by Rust, serialized under the `currentUnit` wire key. */
export interface CurrentUnit {
    index: number;
    total: number;
    title: string;
}

/** Serializable metadata for a single download job (snake_case — default serde). */
export interface DownloadJob {
    id: string;
    url: string;
    title: string | null;
    status: JobStatus;
    progress: number | null;
    speed: string | null;
    eta: string | null;
    error: string | null;
    retryable: boolean;
    started_at: number | null;
    completed_at: number | null;
    output_path: string | null;
    /** Original options used to start this job (populated by backend). */
    options: DownloadOptions | null;
    /** Playlist membership — null for standalone downloads. Omitted in legacy fixtures. */
    playlist?: PlaylistContext | null;
    /** Current post-processing stage label (e.g. "Merging", "Transcoding"); null outside processing. */
    stage: string | null;
    /** Accumulated log messages from download-log events (frontend-only, not from Rust). */
    logMessages?: string[];
    /** Current unit info, owned by Rust (`currentUnit` wire key). Null when no unit is active. */
    currentUnit: CurrentUnit | null;
    /** Live progress fields merged client-side from `download-progress` events
     *  (camelCase wire keys), not part of the Rust DownloadJob serialization.
     *  Undefined until the first progress event lands for the job. */
    totalBytes?: number | null;
    /** True when `totalBytes` is an extrapolated estimate (segmented download). */
    isEstimated?: boolean;
    /** Fragments completed so far (segmented HLS/DASH); null/undefined otherwise. */
    segmentsDownloaded?: number | null;
    /** Total fragment count (segmented HLS/DASH); null/undefined otherwise. */
    totalSegments?: number | null;
}

/**
 * Container formats matching Rust `ContainerFormat` (#[serde(rename_all = "lowercase")]).
 */
export type ContainerFormat =
    | "mp4" | "mkv" | "webm" | "mov" | "ts" | "flv" | "avi"
    | "threegp" | "mpg" | "f4v" | "asf" | "mxf" | "vob" | "dv"
    | "nut" | "ivf" | "ogg" | "m4a" | "mp3" | "wav" | "flac"
    | "opus" | "aac" | "aiff" | "mka" | "wv" | "caf" | "ac3";

/**
 * Audio formats matching Rust `AudioFormat` (#[serde(rename_all = "lowercase")]).
 */
export type AudioFormat =
    | "mp3" | "aac" | "m4a" | "opus" | "vorbis" | "flac" | "alac"
    | "wav" | "ac3" | "eac3" | "dts" | "mp2" | "wavpack" | "tta";

/**
 * Subtitle formats matching Rust `SubtitleFormat` (#[serde(rename_all = "lowercase")]).
 */
export type SubtitleFormat = "srt" | "vtt" | "ass" | "ssa" | "lrc";

/**
 * Frontend-supplied download options.
 *
 * Uses camelCase because the Rust struct has #[serde(rename_all = "camelCase")].
 */
export interface DownloadOptions {
    format: string | null;
    outputDir: string | null;
    subtitles: boolean;
    subtitleLangs: string[];
    remux: ContainerFormat | null;
    extractAudio: AudioFormat | null;
    embedThumbnail: boolean;
    audioMultistreams: boolean;
    recodeVideo: ContainerFormat | null;
    normalizeAudio: boolean | null;
    loudnorm: boolean | null;
    loudnormPreset: string | null;
    loudnormTargetI: number | null;
    loudnormTargetTp: number | null;
    loudnormTargetLra: number | null;
    loudnormDynamic: boolean | null;
    loudnormPrecompress: boolean | null;
    normalizeBoost: boolean | null;
    normalizeBoostDb: number | null;
    embedSubtitles: boolean | null;
    videoEncoder: string | null;
    recodeAudio: RecodeAudioMode | null;
    recodeContainer: string | null;
    verbose: boolean | null;
}

// ========== Queue View Types (frontend-only) ==========

/** Discriminated union for virtualized queue items. */
export type QueueItem =
    | { type: "group-header"; playlistId: string; playlistTitle: string; jobs: DownloadJob[]; collapsed: boolean }
    | { type: "job"; job: DownloadJob; inPlaylist: boolean }
    | { type: "show-more"; playlistId: string; hiddenCount: number };

// ========== Event Payloads (camelCase — Rust uses #[serde(rename_all = "camelCase")]) ==========

/** Download progress payload emitted as "download-progress". */
export interface DownloadProgressPayload {
    jobId: string;
    progress: number;
    speed: string | null;
    eta: string | null;
    downloadedBytes: number;
    totalBytes: number | null;
    /** True when totalBytes is an extrapolated estimate (segmented download).
     *  Rendered as a `~`-prefixed total size in the desktop progress UI. */
    isEstimated: boolean;
    /** Fragments completed so far (segmented HLS/DASH); null for progressive HTTP.
     *  u64 on the wire; JS `number` is safe for fragment counts (always well
     *  under Number.MAX_SAFE_INTEGER — real streams have thousands, not 2^53). */
    segmentsDownloaded: number | null;
    /** Total fragment count (segmented HLS/DASH); null for progressive HTTP. */
    totalSegments: number | null;
}

/** Download completion payload emitted as "download-complete". */
export interface DownloadCompletePayload {
    jobId: string;
    filepath: string;
}

/** Download error payload emitted as "download-error". */
export interface DownloadErrorPayload {
    jobId: string;
    error: string;
    retryable: boolean;
}

/** Download cancellation payload emitted as "download-cancelled". */
export interface DownloadCancelledPayload {
    jobId: string;
}

/** Log message payload emitted as "download-log". */
export interface DownloadLogPayload {
    jobId: string;
    level: "info" | "warn" | "debug";
    message: string;
}

/** Post-processing progress payload emitted as "postprocess-progress". */
export interface PostProcessProgressPayload {
    jobId: string;
    stage: string;
    progress: number; // 0.0–1.0
    eta: string | null;
}

/** Unit-started payload emitted as "unit-started" (playlist episode or merge stream start). */
export interface UnitStartedPayload {
    jobId: string;
    unitIndex: number;
    unitTotal: number;
    unitTitle: string;
}

// ========== Settings Types ==========

/**
 * Application settings that persist between sessions (snake_case — default serde).
 *
 * Rust PathBuf serializes as a string.
 */
export interface AppSettings {
    output_dir: string;
    default_remux: ContainerFormat | null;
    default_extract_audio: AudioFormat | null;
    default_subtitle_format: SubtitleFormat | null;
    default_subtitle_langs: string[];
    embed_thumbnail: boolean;
    write_thumbnail: boolean;
    embed_metadata: boolean;
    verbose: boolean;
    default_search_provider: string | null;
    output_template: string | null;
    cookies_from_browser: string | null;
    cookies_file: string | null;
    proxy: string | null;
    rate_limit: string | null;
    socket_timeout: number | null;
    read_timeout: number | null;
    pool_idle_timeout: number | null;
    download_timeout: number | null;
    merge_timeout: number | null;
    normalize_audio: boolean;
    audio_gain_target: number | null;
    loudnorm: boolean;
    loudnorm_preset: string | null;
    loudnorm_target_i: number | null;
    loudnorm_target_tp: number | null;
    loudnorm_target_lra: number | null;
    loudnorm_dynamic: boolean;
    loudnorm_precompress: boolean;
    normalize_boost: boolean;
    normalize_boost_db: number | null;
    embed_subtitles: boolean;
}

// ========== Error Types ==========

/**
 * Frontend-facing error from Tauri IPC commands.
 *
 * Rust uses #[serde(tag = "kind", content = "data")] so the JSON shape is:
 *   { kind: "NetworkError", data: { message: "...", retryable: true } }
 */
export interface AppError {
    kind: string;
    data: Record<string, unknown>;
}

/** View mode for search results display. */
export type ViewMode = "list" | "grid";
