[package]
name = "rdlp-jsinterp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rdlp-core = { path = "../rdlp-core" }
async-trait = { workspace = true }
tokio = { workspace = true }
boa_engine = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
