"""yt-dlp exception hierarchy mirror — drop-in compatible with `from
yt_dlp.utils import ExtractorError`.

Class shapes verified against yt-dlp tag `2026.03.17`, file
`yt_dlp/utils/_utils.py`:966-1162. The root is `YoutubeDLError`, with
`ExtractorError` and a small handful of siblings (`DownloadError`,
`UnavailableVideoError`, `ContentTooShortError`, `PostProcessingError`,
`DownloadCancelled`). yt-dlp does NOT ship dedicated `AuthRequiredError`,
`NotFoundError`, `RateLimitedError`, `NetworkError`, or `ParseError` —
these failure modes are all `ExtractorError(msg, expected=True)`, dispatched
via `raise_login_required` / `raise_geo_restricted` / `raise_no_formats`
helpers on `InfoExtractor`. Mirror that exactly so ported `.py` files using
`raise ExtractorError("...", cause=e, video_id=vid)` work without
modification.

The `_entry.py` template generated by `rdlp plugin build-from-ytdlp` maps
these exceptions to specific WIT `extract-error` variants — see the
mapping table in that file.
"""


class YoutubeDLError(Exception):
    """Root of yt-dlp's exception hierarchy.

    yt-dlp's `__init__` mirrors `Exception.__init__`; we follow the same
    pattern so `str(e)` and `e.msg` both work.
    """

    def __init__(self, msg=None):
        if msg is not None:
            super().__init__(msg)
            self.msg = msg
        else:
            super().__init__()
            self.msg = None


class ExtractorError(YoutubeDLError):
    """Raised when an extractor cannot produce a usable info-dict.

    Constructor signature matches upstream exactly so ported code using
    `raise ExtractorError("foo", cause=e, video_id=vid, expected=True)`
    works without modification.

    `expected=True` distinguishes "the site told us no" (auth, geo, not
    found, rate-limited — caller should not file a bug report) from
    "the extractor probably has a bug" (`expected=False`, the default).
    The `_entry.py` WIT mapping uses `expected` plus message-text
    heuristics to choose between the `auth-required`, `not-found`,
    `rate-limited`, `parse`, and `internal` variants.
    """

    def __init__(
        self, msg, tb=None, expected=False, cause=None, video_id=None, ie=None
    ):
        super().__init__(msg)
        self.orig_msg = str(msg)
        self.traceback = tb
        self.expected = expected
        self.cause = cause
        self.video_id = video_id
        self.ie = ie
        self.exc_info = None  # set by yt-dlp's __init__ via sys.exc_info();
        # we leave it None — components don't have a useful traceback object
        # to capture across the WIT boundary anyway.


class UnsupportedError(ExtractorError):
    """The given URL doesn't match this extractor's `_VALID_URL`.

    Single-arg constructor matching upstream (`_utils.py:1022-1026`).
    `expected=True` is forced; raising this is never a bug report.
    """

    def __init__(self, url):
        super().__init__("Unsupported URL: %s" % url, expected=True)
        self.url = url


class RegexNotFoundError(ExtractorError):
    """Raised by `_search_regex` when nothing matched and `fatal=True`.

    Subclass marker only — no extra fields. Maps to `extract-error::parse`.
    """


class GeoRestrictedError(ExtractorError):
    """Content is geo-restricted; `countries` is the allowed-country list.

    Constructor matches upstream (`_utils.py:1034-1044`). `expected=True`
    is forced. The host's WIT mapping treats this as `auth-required` for
    Slice 1 (no dedicated `geo-restricted` variant in the current WIT);
    a Slice-2 WIT bump can add the variant if needed.
    """

    def __init__(self, msg, countries=None, **kwargs):
        kwargs.setdefault("expected", True)
        super().__init__(msg, **kwargs)
        self.countries = countries


class UserNotLive(ExtractorError):
    """The channel is not currently live (matches upstream
    `_utils.py:1047-1052`)."""

    def __init__(self, msg=None, **kwargs):
        kwargs.setdefault("expected", True)
        super().__init__(msg or "The channel is not currently live", **kwargs)


class DownloadError(YoutubeDLError):
    """Sibling of `ExtractorError`, NOT a subclass. Raised by the downloader
    layer (`_utils.py:1055-1066`); extractors normally don't raise this but
    some defensive code catches it.
    """

    def __init__(self, msg, exc_info=None):
        super().__init__(msg)
        self.exc_info = exc_info


class UnavailableVideoError(YoutubeDLError):
    """Sibling, raised by `YoutubeDL.process_info` when a format is
    unavailable (`_utils.py:1136-1147`). Not raised from `_real_extract`."""

    def __init__(self, err=None):
        super().__init__("Unable to download video" if err is None else str(err))


class ContentTooShortError(YoutubeDLError):
    """Sibling, raised by the downloader on truncated downloads
    (`_utils.py:1150-1162`).
    """

    def __init__(self, downloaded, expected):
        super().__init__(
            "Downloaded %d bytes, expected %d bytes" % (downloaded, expected)
        )
        self.downloaded = downloaded
        self.expected = expected


class PostProcessingError(YoutubeDLError):
    """Stub. yt-dlp postprocessing isn't run inside the plugin sandbox; the
    class exists so `from yt_dlp.utils import PostProcessingError` resolves
    in ported code that imports-and-passes-through."""


class DownloadCancelled(YoutubeDLError):
    """Cancellation signal (epoch deadline, user abort). Maps to WIT
    `extract-error::cancelled`. Upstream subclasses (`ExistingVideoReached`,
    `RejectedVideoReached`, `MaxDownloadsReached`) are not ported — they're
    YoutubeDL-process-control signals, not extractor outputs.
    """


# Network exceptions yt-dlp's ExtractorError auto-wraps (`_utils.py:986`).
# We don't ship the actual urllib/http.client classes, but exposing the
# tuple lets caller code do `isinstance(e, network_exceptions)` symmetrically.
# Slice-1 implementation: empty tuple. The host's `_check_status`
# RuntimeError is the network-failure surface inside the runtime; the
# `_entry.py` template recognises RuntimeError("HTTP ...") explicitly.
network_exceptions = ()
