"""Thin wrappers around the WIT host imports.

These imports are intentionally module-level (componentize-py issue #23 forbids
lazy imports). Outside a componentize-py-built component, `extractor_plugin`
(the renamed wit_world) doesn't exist — we catch `ModuleNotFoundError` so
unit tests can still import this module without crashing.

We catch the narrower `ModuleNotFoundError` rather than the broader
`ImportError` so that real bugs in the bindings module (e.g. partial
componentize-py output, a syntax error in a re-exported module) surface as
errors at module-load time rather than silently flipping us to "outside
runtime" mode and producing a plugin that emits no logs. I/O helpers raise
at call time when not available.
"""

import logging as _logging
import re as _re

_outside_runtime_logger = _logging.getLogger('rdlp_ytdlp_compat')

# `extractor_plugin.*` is generated by componentize-py at WASM-build time and is
# not present in a plain CPython environment; mypy / standalone test runs ignore
# the missing module. Runtime guards via try/except handle the missing case.
try:
    from extractor_plugin.imports import host_fetch, host_log  # type: ignore[import-not-found]
    from extractor_plugin.imports.host_fetch import Request as _Request  # type: ignore[import-not-found]

    _AVAILABLE = True
except ModuleNotFoundError:
    _AVAILABLE = False

try:
    from extractor_plugin.imports import host_extract_helpers as _hxh

    _HXH_AVAILABLE = True
except ModuleNotFoundError:
    _hxh = None
    _HXH_AVAILABLE = False


class HostHttpError(RuntimeError):
    """Non-2xx HTTP response from `host:fetch`.

    Carries `status` (int) and `url` (str) as typed attributes so the
    `_entry.py` WIT-variant dispatcher can route by status code via
    `isinstance` rather than parsing the message string. Subclasses
    `RuntimeError` so existing `except RuntimeError:` clauses still catch
    it (including ported yt-dlp code that catches RuntimeError defensively).
    """

    def __init__(self, status: int, url: str):
        super().__init__(f'HTTP {status} fetching {url}')
        self.status = status
        self.url = url


def _check_status(status: int, expected_status: int | None, url: str) -> None:
    """Raise `HostHttpError` if `status` is not 2xx and is not the explicitly-
    allowed `expected_status`. Extracted for unit-testability — without
    componentize-py bindings present, the surrounding `fetch_text` cannot be
    called directly, but this pure-Python predicate can be exercised in tests
    to pin the contract.

    NOTE: This is a status-code-only check. Sites that respond `200 OK` with
    HTML for a login wall / soft-paywall are NOT detected here — that's the
    extractor's responsibility (e.g. by looking for a known login-form
    selector and calling `self.raise_login_required()`). The host can't
    reliably distinguish "real content with embedded JS check" from "login
    wall served as 200" without parsing the body.

    Callers that need to inspect a specific non-2xx (e.g. yt-dlp's
    `expected_status=404` for soft 404s) pass that integer; everything else
    in the non-2xx range raises.
    """
    if 200 <= status < 300:
        return
    if expected_status is not None and status == expected_status:
        return
    raise HostHttpError(status, url)


def fetch_text(
    url: str,
    headers: list[tuple[str, str]] | None = None,
    timeout_ms: int = 30000,
    expected_status: int | None = None,
) -> str:
    """Fetch a URL and return the body decoded as UTF-8 text.

    Raises `HostHttpError` if the HTTP status is not 2xx (and not equal to
    `expected_status` if supplied). The error carries `.status` as a typed
    attribute so the WIT dispatcher can route by status code without
    inspecting message strings.

    SCOPE: This guards against status-driven failure modes (4xx/5xx bodies
    masquerading as content). It does NOT detect 200-OK login-wall HTML
    pages; extractors must do that themselves and call
    `self.raise_login_required()` when their content-shape check fails.
    """
    if not _AVAILABLE:
        raise RuntimeError('_host.fetch_text called outside componentize-py runtime')
    req = _Request(
        url=url,
        method='GET',
        headers=headers or [],
        body=None,
        timeout_ms=timeout_ms,
    )
    resp = host_fetch.fetch(req)
    _check_status(resp.status, expected_status, url)
    return bytes(resp.body).decode('utf-8', errors='replace')


def log(level: str, message: str) -> None:
    """Forward a log line to the host. Outside the runtime, route through
    the stdlib `logging` module on the `rdlp_ytdlp_compat` logger so test
    harnesses (pytest's `caplog`) can assert on warning/error lines instead
    of silently swallowing them."""
    if not _AVAILABLE:
        # pytest captures via stdlib logging; route through it so test runs
        # surface extractor diagnostics. Map our level vocabulary to logging.
        level_map_stdlib = {
            'trace': _logging.DEBUG,
            'debug': _logging.DEBUG,
            'info': _logging.INFO,
            'warn': _logging.WARNING,
            'error': _logging.ERROR,
        }
        _outside_runtime_logger.log(level_map_stdlib.get(level, _logging.INFO), message)
        return
    level_map = {
        'trace': host_log.Level.TRACE,
        'debug': host_log.Level.DEBUG,
        'info': host_log.Level.INFO,
        'warn': host_log.Level.WARN,
        'error': host_log.Level.ERROR,
    }
    host_log.log(level_map.get(level, host_log.Level.INFO), message)


# ── Slice 2.5 host-extract-helpers facade ──────────────────────────
# Wraps the componentize-py-emitted bindings into ergonomic
# `_host.search_regex(...)` calls. Plugins never touch
# `extractor_plugin.imports.host_extract_helpers` directly.
#
# All functions guard with `_HXH_AVAILABLE` at call time — the same
# pattern as fetch_text/_AVAILABLE above — so unit tests can import
# this module without crashing.


def _re_flags_to_wit(flags):
    """Translate Python `re.IGNORECASE | re.MULTILINE | re.DOTALL |
    re.VERBOSE` int to WIT RegexFlags. Returns 0-valued flags when
    the bindings are unavailable (callers gate on _HXH_AVAILABLE)."""
    if flags is None or flags == 0:
        return _hxh.RegexFlags(0) if _HXH_AVAILABLE else 0
    out = 0
    if flags & _re.IGNORECASE:
        out |= 1 << 0
    if flags & _re.MULTILINE:
        out |= 1 << 1
    if flags & _re.DOTALL:
        out |= 1 << 2
    if flags & _re.VERBOSE:
        out |= 1 << 3
    return _hxh.RegexFlags(out) if _HXH_AVAILABLE else out


def search_regex(pattern, string, flags=0):
    """Return the first match of `pattern` in `string`, or None."""
    if not _HXH_AVAILABLE:
        raise RuntimeError('_host.search_regex called outside componentize-py runtime')
    return _hxh.search_regex(pattern, string, _re_flags_to_wit(flags))


def html_search_regex(pattern, string, flags=0):
    """Search for `pattern` in `string` after stripping HTML tags."""
    if not _HXH_AVAILABLE:
        raise RuntimeError('_host.html_search_regex called outside componentize-py runtime')
    return _hxh.html_search_regex(pattern, string, _re_flags_to_wit(flags))


def html_search_meta(name, html):
    """Extract a ``<meta name="…" content="…">`` value from `html`."""
    if not _HXH_AVAILABLE:
        raise RuntimeError('_host.html_search_meta called outside componentize-py runtime')
    return _hxh.html_search_meta(name, html)


def og_search_property(prop, html):
    """Extract an Open Graph ``<meta property="og:…" content="…">`` value."""
    if not _HXH_AVAILABLE:
        raise RuntimeError('_host.og_search_property called outside componentize-py runtime')
    return _hxh.og_search_property(prop, html)


def rta_search(html):
    """Return True if `html` contains a RTA (Restricted to Adults) label."""
    if not _HXH_AVAILABLE:
        raise RuntimeError('_host.rta_search called outside componentize-py runtime')
    return _hxh.rta_search(html)


def search_json(start_pattern, end_pattern, string):
    """Extract a JSON object delimited by `start_pattern` … `end_pattern`."""
    if not _HXH_AVAILABLE:
        raise RuntimeError('_host.search_json called outside componentize-py runtime')
    return _hxh.search_json(start_pattern, end_pattern, string)


def extract_m3u8(url, video_id, *, ext=None, protocol=None, m3u8_id=None, fatal=True):
    """Parse an M3U8 playlist and return a list of Format dicts."""
    if not _HXH_AVAILABLE:
        raise RuntimeError('_host.extract_m3u8 called outside componentize-py runtime')
    opts = _hxh.M3u8Options(ext=ext, protocol=protocol, m3u8_id=m3u8_id, fatal=fatal)
    return _hxh.extract_m3u8(url, video_id, opts)


def extract_mpd(url, video_id, *, mpd_id=None, fatal=True):
    """Parse a DASH MPD via the host helper. Returns MpdExtraction."""
    if not _HXH_AVAILABLE:
        raise RuntimeError(
            "_host.extract_mpd called outside componentize-py runtime"
        )
    opts = _hxh.MpdOptions(mpd_id=mpd_id, fatal=fatal)
    return _hxh.extract_mpd(url, video_id, opts)


def extract_json_ld(html):
    """Extract structured data from JSON-LD ``<script>`` blocks in `html`."""
    if not _HXH_AVAILABLE:
        raise RuntimeError('_host.extract_json_ld called outside componentize-py runtime')
    return _hxh.extract_json_ld(html)


class Cookie:
    """Simple cookie record — used by `_set_cookie` to avoid importing the
    WIT-generated Cookie type in unit tests (outside componentize-py)."""

    def __init__(self, *, name, value, domain, path='/', secure=False, http_only=False, expires=None):
        self.name = name
        self.value = value
        self.domain = domain
        self.path = path
        self.secure = secure
        self.http_only = http_only
        self.expires = expires


class _CookieJarFacade:
    """Lazy facade — actual cookie-jar bindings live at extractor_plugin.imports.host_cookie_jar."""

    def set_cookie(self, url, cookie):
        from extractor_plugin.imports import host_cookie_jar

        return host_cookie_jar.set_cookie(url, cookie)

    def get_cookies(self, url):
        from extractor_plugin.imports import host_cookie_jar

        return host_cookie_jar.get_cookies(url)


cookie_jar = _CookieJarFacade()
