[package]
name = "rdlp-http"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rdlp-types = { path = "../rdlp-types" }
wreq = { workspace = true }
wreq-util = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
