[package]
name = "rdlp-table"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rdlp-types = { path = "../rdlp-types" }
tabled = { workspace = true }
console = { workspace = true }
terminal_size = { workspace = true }

[lints]
workspace = true
